# Generated by Django 5.0.6 on 2024-05-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
