# Generated by Django 5.0.6 on 2024-05-27 23:22

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
