# Generated by Django 5.0.6 on 2024-05-27 23:26

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_post_youtube_link_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, max_length=800, null=True),
        ),
    ]
