# Generated by Django 5.0.6 on 2024-05-28 20:32

import django_resized.forms
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='postImages/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, max_length=500, null=True),
        ),
    ]
