# Generated by Django 5.0.6 on 2024-05-30 13:26

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_post_image_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.jpg', force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[400, None], upload_to='postImages/'),
        ),
    ]
